- name: Debug Secrets
  run: |
    echo "JIRA_BASE_URL=${{ secrets.JIRA_URL }}"
    echo "JIRA_EMAIL=${{ secrets.JIRA_EMAIL }}"
    # echo "JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}" # Do not print sensitive information
